### ISSUE TITLE
Unused Branches

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#160]
@pablosaraiva @toadgeek Tem uma branch no repo principal que se chama `toadgeek`, não sei pra que serve, mas como vocês criaram e subiram, melhor vocês tomarem uma decisão. Revisar, se tiver algo pra jogar pra `master` que o façam, e se for inútil/antiga, ela poderia ser deletada. :smile:

**Comment by pablosaraiva** [comment]
Pode apagar. Foi uma tentativa que acabou não indo pra frente.

Em seg, 18 de abr de 2016 13:30, StefanWerW notifications@github.com
escreveu:
