### ISSUE TITLE
Proposta de limpar o Hero.cs script

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#164]
Com objetivo de deixar o Hero.cs mais limpo e de fácil leitura e compreendimento, estava pensando se não poderíamos mover algumas funções que não são diretamente ligadas ao Hero para seus respectivos componentes e elementos do jogo. Minhas sugestões:
- [ ]  `void TouchedForceField ()` poderia ser um effector diretamento no prefab ForceField
- [x] o `void TrampolineJump (float multiplier)` poderia ser implementado diretamente num script no trampolim
- [x] o `private void DoAction ()` poderia ser um método que manda um sinal pros elementos, e esses resolvem se necessário. Evitando o formato `switch case` aonde teríamos que hardcode cada cenário usando tags. Acho que fica mais limpo cada elemento, por exemplo a alavanca, fazer a ação quando recebe esse comando.
- [x] mover todos os métodos e parâmetros relacionados a carregar para um script separado, algo como HeroCarry.cs, ou HeroCarryBehaviour.cs .
- [x] identificar se herói é forte ou rapido, usando um método como `abstract bool isStrong();` em vez de um parâmetro serializado.

Gostaria da opiniões, sugestões e criticas.

**Comment by ednaldomoreira** [comment]
O método
    public Collider2D GetColliderObjNext(ObjPositionRelHero objPos);

Pode ser Static e ir para uma classe só de reutilização, tipo uma Math ?

**Comment by ldamota** [comment]
Podemos renomear TrampolineJump para Jump mesmo e deixar as duas implementações possíveis, com ou sem multiplicador. Ela utiliza cálculos que já estão sendo feitos no Hero.cs então ficaria um pouco redundante fazer novamente no outro script. Ou MultipliedJump algo assim.

**Comment by StefanWerW** [comment]
@ednaldomoreira concordo transformar num static. Podemos criar uma pasta com esses `utils` scripts, classes, etc.

**Comment by StefanWerW** [comment]
@ldamota voce esta propondo ter:

``` C#
void Jump(){
    Jump(1);
}
void Jump(float factor){
    //calculo longo e pulo aqui
    //...
}
```

Isso?

**Comment by ednaldomoreira** [comment]
@ldamota A idéia de @StefanWerW é que o trampolim impulsione os heróis e não que eles pulem mais alto, por isso o que ele propõe é que o trampolim dê um AddForce nos heróis.

**Comment by ldamota** [comment]
@StefanWerW Precisamente. Minha ideia original era implementar dessa forma, mas não quis alterar a void Jump() antes de outra pessoa testar o código. @ednaldomoreira Entendi a ideia, sugeri apenas dessa forma pois o cálculo da força para se atingir uma altura determinada no Hero.cs utiliza métodos e variáveis privadas e, como o game design orientou que o pulo do trampolim se baseasse na altura do pulo de cada Herói, achei mais prático termos as duas implementações possíveis para Jump() e isso custaria apenas 3 linhas a mais. Outra vantagem é flexibilidade para utilizar esse método em outras situações como um ataque de um boss ou algum powerup.

Por outro lado poderia ser interessante refazer esses cálculos no trampolim em si caso exista a necessidade de outros tipos de objetos serem lançados.

**Comment by ednaldomoreira** [comment]
Em alguns games a força do pulo do herói e a força que o trampolim aplica a ele se somam. Do jeito que foi implementado fica uma força ou outra.

**Comment by ednaldomoreira** [comment]
Podemos transformar esses trechos do código do herói em um método AddForce ?

Do Método Jump

``` C#
foreach (Rigidbody2D rg2d in transform.GetComponentsInChildren<Rigidbody2D>())
    rg2d.velocity = new Vector2 (rigidBody2D.velocity.x, 0);
rigidBody2D.AddForce (new Vector2 (0f, (float)jumpForce), ForceMode2D.Impulse);
```

Do Método TouchedForceField

``` C#
rigidBody2D.AddForce (new Vector2 (facingDirection * maxWalkingSpeed * speed, 0), ForceMode2D.Impulse);
```

E utilizar nos elementos Trampoline e TouchedForceField, que aplicam força nos heróis ?

Pensei para resolver isso:
- void TouchedForceField () poderia ser um effector diretamento no prefab ForceField
- o void TrampolineJump (float multiplier) poderia ser implementado diretamente num script no trampolim

**Comment by ldamota** [comment]
@ednaldomoreira O problema do cálculo da força necessária para se atingir determinado multiplicador da altura máxima de pulo (pedido do game design) permanece. Alguma ideia para contornar isso sem duplicar muito código? Caso seja apenas um problema de não somar a força do trampolim com o pulo é só somar 1 ao multiplicador do Jump (float multiplier) caso o jogado aperte o botão de pulo.

**Comment by StefanWerW** [comment]
@ednaldomoreira quantos porcento está concluída essa tarefa? Sera que tem como criar um checklist, ou fazer um update no que ta la no comentário original. Podemos ainda fechar esse issue e abrir outro com esse checklist e tal. O que me diz?

**Comment by ednaldomoreira** [comment]
@StefanWerW só falta
'void TouchedForceField () poderia ser um effector diretamento no prefab ForceField'

**Comment by StefanWerW** [comment]
Tudo feito. Só falta #221.
