### ISSUE TITLE
Parameter 'climb' and 'stopclimb' does not exist

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#172]
Unity esta dando esses warning na inicialização.

> Parameter 'climb' does not exist.
> UnityEngine.Animator:SetBool(String, Boolean)
> Hero:VerticalMove(Single) (at Assets/Scripts/Hero/Hero.cs:191)
> HeroControl:FixedUpdate() (at Assets/Scripts/Hero/HeroControl.cs:112)

e

> Parameter 'stopclimb' does not exist.
> UnityEngine.Animator:SetBool(String, Boolean)
> Hero:VerticalMove(Single) (at Assets/Scripts/Hero/Hero.cs:192)
> HeroControl:FixedUpdate() (at Assets/Scripts/Hero/HeroControl.cs:112)

**Comment by ednaldomoreira** [comment]
Vou criar uma atividade para animar os heróis quando estiver subindo(climb) e parado(stopclimb). Podemos comentar esse comando e sinalizar que vai ser feita a trsnsição de estado do animator.
