### ISSUE TITLE
Esteira

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#179]
Lista de vários problemas:
- [ ]  Os pedacinhos da esteiras não estão se movendo.
- [ ]  O herói quando esta em cima da esteira se move automaticamente, e não pelos pedaços.
- [ ]  O herói não esta conseguindo pular quando em cima da esteira
- [ ]  O script pode estender ActionableElement, sendo assim passives de ser acionado e desligado por outros triggers
- [ ]  Velocidade poderia ser um parâmetro
- [ ]  O script e o prefab estão em português, assim como todos os parâmetros no script. Esses devem ser transformados em inglês (travelator pode ser usado como nome, e excluir o que ja foi feito nesse nome)
- [ ]  O tamanho da esteira poderia ser variável, e editável no editor.

Gostaria da opinião de @ednaldomoreira , ja que foi ele que trabalhou bastante nesse assunto.

**Comment by ednaldomoreira** [comment]
@StefanWerW sim concordo, foi o segundo elemento que criei, e ficou algumas pendências. Para dizer a verdade acho que deveríamos criar uma esteira mais simples onde os mecanismos da movimentação poderia ser feita por animações mesmo, em vez de um.gameobject por cada parte.

**Comment by StefanWerW** [comment]
Eu gosto do modo que estava sendo feito, mas acho que se optarmos por um jeito mais simples é ok também.

**Comment by pedrobueno** [comment]
@StefanWerW e @ednaldomoreira sabem como está o status dessa issue? Posso criar um card no trello e fazer esses items ai da lista?

**Comment by ednaldomoreira** [comment]
@pedrobueno já está em andamento com o @ldamota 
https://trello.com/c/igPkWh3K/148-esteira-issue-179

**Comment by pedrobueno** [comment]
Uma idéia..poderia tem uma tag nas issues pra gente saber se ela já está sendo feita né? ;)

**Comment by ednaldomoreira** [comment]
Na verdade o acompanhamento é no trello, mas como o github tem o issues estamos usando os dois, eu acho que deveriamos usar o issues para reportar os problemas no projeto e o trello para acompanhar as atividades, já que um issue pode gerar várias tarefas.

Já iniciei uma discussão sobre trello x issues
https://trello.com/c/yJ6LH3cw/77-discussao-sobre-a-organizacao

**Comment by pedrobueno** [comment]
Sim, eu já li essa tread, só comentei sobre as tags pq eu to procurando algo pra fazer, dai tenho que ficar alternando entre issues e trello pra saber qual já foi começada e qual ainda não... poderia mudar o status da issue para algo diferente de open, ou algo parecido, pra ajudar nessa hora de ver o que precisa ser feito ainda.... só uma idéia =)

**Comment by otaconwow** [comment]
Concordo com o ponto do @phbueno, existem até projetos externos onde o pessoal cria uma tag de "In progress" e "Pending" pra indicar se já foi iniciado algum trabalho na Issue ou não,

Segue: https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

**Comment by ldamota** [comment]
Me parece uma boa ideia poder ver por aqui quais já estão sendo trabalhadas, a não ser que todas as issues já fossem sempre para o trello assim que abertas.

**Comment by ednaldomoreira** [comment]
Os outros membros da muvuca, que não são da programação, usa o trello para acompanhar as atividades, o que justifica a programação ter que usar outra forma de controlar as suas atividades ? Aí fica fora de padrão  e fica a informação em dois lugares distintos.

**Comment by pedrobueno** [comment]
Você diz pra não ficar informação duplicada? Por que da mesma forma vamos criar os cards no trello para que todos saibam o que está acontecendo... mas facilitaria pra gente saber o que precisa ser feito ainda das issues...

**Comment by ednaldomoreira** [comment]
Não falo de informação duplicada, mas lista de atividades em dois lugares. Quem procura por atividades vai ter que procurar no trello e no github. Por que não deixar em um lugar só ?

**Comment by otaconwow** [comment]
Mas atualmente está gerando problema nesse ponto, por exemplo, as vezes são criadas tarefas referentes as Issues para o pessoal do board Muvuca Iniciante e não tem nenhuma referência disso aqui ou no board de programação. Se algum membro do board de programação for olhar o github ou o trello (board de programação), vai ver que não tem ninguem trabalhando e vai criar outro card, gerando dois cards iguais em boards diferentes.
Se a gente apenas marcar a Issue, indicando que ninguem iniciou nenhum tipo de trabalho em cima dela, já facilita para que o colaborador encontre as Issues que estão pendentes.
Quando o trabalho for iniciado, é criado o card no trello para acompanhamento da atividade etc.

**Comment by StefanWerW** [comment]
E ai @ednaldomoreira , o que vai ser feito da esteira que voce tinha criado?

**Comment by StefanWerW** [comment]
![img](http://i.giphy.com/41I5c7m6CNqHm.gif)

**Comment by ednaldomoreira** [comment]
Qual a diferença da esteira para o travelator ?

**Comment by StefanWerW** [comment]
Exatamente. Voce criou a Esteira, e esse travelator ja existia. Agora temos que ver qual fica, qual é removido. E se ficar o Esteira, temos que renomear. Alem de estar na linguá errada (tem que ser inglês), pode influenciar novatos a nomear coisas em português. Sei que um dos dois foi modificado recentemente. Temos que ver. E como voce criou a esteira, acho que se deve ser removido, cabe a voce. :smile:
