### ISSUE TITLE
Prefabs dos Elementos fora da norma

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#180]
Ha vários prefabs que estão fora na norma.
Por exemplo, não esta com o transform root em:
-  `position 0 0 0`
- `rotation 0 0 0` 
- `scale 1 1 1`

**Comment by ednaldomoreira** [comment]
@guilhermercaetano o puzzle das cores está com scale 2 2 2, tentei corrigir alterando no prefab e ele alterou o tamanho dos gameobjects filhos. Vc pode corrigir isso para poder fechar essa issues ?

**Comment by guilhermercaetano** [comment]
Eu esqueci de olhar a escala desse. Já vou corrigir

**Comment by StefanWerW** [comment]
Podemos fechar?

**Comment by ednaldomoreira** [comment]
Não, a garra tá com position fora da norma, eu vou fazer um pull request dando Close no titulo, aí fecha né ?

**Comment by StefanWerW** [comment]
@ednaldomoreira  Nao no titulo! Na mensagem no commit ou do PR! https://help.github.com/articles/closing-issues-via-commit-messages/
