### ISSUE TITLE
Escada acionavel em portugues

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#181]
Os elementos, prefabs e scripts devem estar em inglês.

Acredito que @otaconwow criou esses elementos, se voce ou outro pudesse modificalos, seria otimo. :smile:

**Comment by otaconwow** [comment]
@StefanWerW  Pode deixar, vou fazer o ajuste e envio PR.

**Comment by otaconwow** [comment]
@StefanWerW  @ednaldomoreira O PR com a correção foi merged, acredito que essa Issue possa ser fechada.

**Comment by StefanWerW** [comment]
@otaconwow Legal. Vou dar uma pequena dica. Quando criar um PR que concerta um Issue, voce pode incluir no comentário o seguinte text `fix #181` ou `fixes #195` ou `close #191` e quando ele for aceito ele automaticamente vai ser referenciado no Issue e esse ultimo fechado. Ver a [lista completa](https://help.github.com/articles/closing-issues-via-commit-messages/) de palavras que fecham o issue.

**Comment by otaconwow** [comment]
@StefanWerW beleza, n sabia disso, tks.
