### ISSUE TITLE
Activator

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#191]
Tem uma classe no System chamada Activator, e nos temos uma classe também chamada activator. Pode gerar conflitos como gerou quando importamos o plugin Tiled2Unity.

Devemos renomear o Activator? Talvez algo como ElementActivator?

**Comment by ldamota** [comment]
E namespaces? Pensei nisso outro dia, várias das funções podem dar conflito com outros plugins.

**Comment by StefanWerW** [comment]
@ldamota Podemos usar. Espero que isso não confunda mais a vida de novatos.

**Comment by ednaldomoreira** [comment]
@StefanWerW  vamos renomear para ElementActivator então ?
