### ISSUE TITLE
Classe Hero.cs apresentando erros NullReferenceException ao tentar pular(Hero.Jump()) ou alternar personagem (Hero.FixedUpdate).

### ISSUE THREAD

**Issue by otaconwow** [MuvucaGames/MuvucaGame01#194]
Ao tentar pular ou apertar TAB, o Unity dispara erro de NullReferenceException, conforme descrição abaixo.
NullReferenceException: Object reference not set to an instance of an object
Hero.Jump () (at Assets/Scripts/Hero/Hero.cs:213)
HeroControl.FixedUpdate () (at Assets/Scripts/Hero/HeroControl.cs:97)

Hero.StandUp() erro:
NullReferenceException: Object reference not set to an instance of an object
Hero.StandUp () (at Assets/Scripts/Hero/Hero.cs:251)
HeroControl.FixedUpdate () (at Assets/Scripts/Hero/HeroControl.cs:82)

Print:

![image](https://cloud.githubusercontent.com/assets/5216042/14936880/d2d06358-0ecd-11e6-952a-b04358e5cd8f.png)

**Comment by StefanWerW** [comment]
Mas voce tinha os dois herois an cena?

**Comment by otaconwow** [comment]
Sim, eu removi depois pra fazer outros testes.

**Comment by StefanWerW** [comment]
E quando esse erro aparece? Quando tem só herói? So o pequeno? Ou quando os dois estão juntos também ta rolando?

**Comment by otaconwow** [comment]
só quando tem herói, qualquer um deles, acontece com os dois na cena ou separados.

![image](https://cloud.githubusercontent.com/assets/5216042/14937099/54f3f6d8-0ed3-11e6-8208-27d72e1df601.png)

**Comment by ednaldomoreira** [comment]
@StefanWerW  @otaconwow Esse erro acontece no código

```
        SoundManager.Instance.SendMessage ("PlaySFXJump");
```

Isso se deva a falta do Elemento Managers na  scene

**Comment by StefanWerW** [comment]
De fato. O PR #193 (quase pronto) vai resolver isso parcialmente, assegurando um jeito simple e rapido de colocar todos os elementos essenciais na scene.

**Comment by ednaldomoreira** [comment]
@otaconwow @StefanWerW Isso é algo que pode estar no wiki de programação
