### ISSUE TITLE
Remover utilização de TAGS

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#197]
Quero aqui ver a opinião de todos. Mas coloco minha posição em remover por completo o uso de tags. No momento estamos usando tags para:
- Checkpoint
- CheckpointManager
- Lever
- CarringObjectLight
- CarringObjectHeavy
- Box
- Ladder

Pq sou contra? Vários motivos:
- Primeiramente pq cada gameObject só pode ter uma Tag, e como não está definido para que vamos usar, acabamos chegando em conflitos. Exemplo: e se a caixa for um elento carregavel level. Qual das duas tags existentes deveriamos colocar?
- Existe uma vantagem em usar `components`(lembrando que scripts são componentes). Podemos adicionar quantos forem necessários a um gameObject. Podemos ter Inheritance. Por exemplo: Podemos substituir as tags `CarringObjectLight` e `CarringObjectHeavy` por uma classe/script/component abstrata CarringObject, e duas extensões CarringObjectLight e outra Heavy. Podem ser scripts vazios, não pesando no runtime do jogo, mas sendo facilmente detectaveis como as tags.
- Refactor. Quando desejamos trocar o nome de uma Tag, não sabemos aonde e se ela está sendo utilizada. Se for component/script/classe, quando fizermos um refactor, ele trocara todas as referencias automaticamente, e se não, lançará um erro por não existir tal classe. Ja o uso de uma tag inexistente quebra a mecanica do jogo mas não lança erro.

Me digam os seus pontos de vista no assunto. :smile:

**Comment by otaconwow** [comment]
Então @StefanWerW , tava dando uma lida aqui sobre o uso das tags (até pq não manjo mto de Unity ainda e fui buscar o propósito do uso deste recurso) e acredito que seguirmos para a utilização de herança etc seja o caminho. Creio que se utilizarmos os recursos de OOP já nos garante a distinção de objetos e nos da maior flexibilidade.

Além disso, a utilização de tags torna a programação "String based", fazendo com que a gente precise "chumbar" o valor no código, gerando o problema q vc mencionou de quebrar as coisas em caso de um rename etc.

Pelo que eu pesquisei a comunidade também prefere o uso dos recursos que OOP oferece do que utilizar tags, até dizendo que o Unity disponiliza as tags apenas para facilitar o uso por pessoas novas que ainda não estão familiarizadas com estes conceitos. Não sei até que ponto isso é verdade :).

Resumindo, apoio a ideia.
