### ISSUE TITLE
Throw specific error on singleton nullException get

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#207]
Cada singleton do projeto (Exemplo: SoundManager), deve lançar um erro especifico quando o alguém fizer um get do instance e esse não tiver sido inicializado.

**Comment by guilhermercaetano** [comment]
Pra resolver esse caso acredito que poderia ser um Assert usado. Ele pode ou não interrromper o fluxo de execução, isso depende de uma configuração só. Daí poderíamos substituir em um trecho como
`get
        {
            return instance;
        }`
por
`get
        {
            Assert.IsNotNull(instance);
            return instance;
        }`

A questão é que isso só funcionaria se antes da inicialização propriamente dita ele "inicializasse" com null.
`private static SoundManager instance = null;` 

 E também lembrar de adicionar no cabeçalho:
`using UnityEngine.Assertions`

**Comment by guilhermercaetano** [comment]
A solução que eu implementei foi com base nessa #218

**Comment by guilhermercaetano** [comment]
Fazendo alguns testes, descobri que existe uma alternativa mais simples usando o método `Debug.AssertFormat`
Produz o mesmo resultado apenas com uma linha.
`Debug.AssertFormat(instance != null, "Instance of SoundManager is not initialized");`

**Comment by StefanWerW** [comment]
Legal. Voce vai modificar o #218 ?

**Comment by guilhermercaetano** [comment]
Sim, acabei de subir o commit.
