### ISSUE TITLE
Bug ao carregar caixa

### ISSUE THREAD

**Issue by jvmaia** [MuvucaGames/MuvucaGame01#226]
Bug ao usar a ferramenta de carregar caixa, quando a caixa está abaixo de um muro, a caixa fica acima do muro e o herói fica embaixo.
-O herói consegue carregar a caixa mesmo durante esse bug.
-Ao sair do muro a caixa volta ao lugar padrão de quando é carregada.
![bug](https://cloud.githubusercontent.com/assets/13905466/15276674/863ec954-1ac5-11e6-9b8d-e2c2ed41ce90.png)

**Comment by jvmaia** [comment]
@StefanWerW Precisa criar a tarefa no trello?

**Comment by otaconwow** [comment]
@JvMaiia Acredito que a orientação seja criar o card quando for iniciar a tarefa. Segundo o card: https://trello.com/c/u0UMZuLQ/141-outras-atividades-issues-github :+1:

**Comment by jvmaia** [comment]
@otaconwow Valeu :)
