### ISSUE TITLE
Garra é ativada ao pressionar botão de troca de personagem.

### ISSUE THREAD

**Issue by otaconwow** [MuvucaGames/MuvucaGame01#232]
A garra está sendo ativada quando utilizamos o botão para trocar de herói (TAB), ao invés de usar o botão de ação (E).

**Comment by guilhermercaetano** [comment]
Eu tô trabalhando com a garra, e a mudança desse detalhe já está em andamento. Nos próximos dias devo concluir.

**Comment by ednaldomoreira** [comment]
@guilhermercaetano  podemos fechar essa issue ?

**Comment by guilhermercaetano** [comment]
podemos sim
