### ISSUE TITLE
Sprite do Herói trava ao agachar e ficar em pé carregando uma caixa.

### ISSUE THREAD

**Issue by otaconwow** [MuvucaGames/MuvucaGame01#242]
Sprite do Herói trava ao agachar e ficar em pé carregando uma caixa (repetidas vezes).

![image](https://cloud.githubusercontent.com/assets/5216042/16213575/e2dba9ac-3726-11e6-9e21-258770b6b893.png)

**Comment by StefanWerW** [comment]
@otaconwow ve se voce consegue editar os labels agora

**Comment by otaconwow** [comment]
@StefanWerW  Agora sim!

**Comment by ednaldomoreira** [comment]
Acho que esse problema se encaixa no que tinha sido relatado no issue #240. A resolução vai afetar os dois issues, quem for pegar esse, já manda dar close em ambos.

**Comment by StefanWerW** [comment]
Vou fechar esse porque o #240 ta mais explicativo.
