### ISSUE TITLE
RigidBody que segue game objects

### ISSUE THREAD

**Issue by ednaldomoreira** [MuvucaGames/MuvucaGame01#269]
Em conversa no PR #267 surgiu essa idéia de se "criar um rigidbody2d que seguiria qualquer gameObject, dando assim mais flexibilidade pro GD".

**Comment by guilhermercaetano** [comment]
@ednaldomoreira Esse Rigidbody vai tem colisão com alguma coisa?

**Comment by ednaldomoreira** [comment]
Acho que não, o objetivo dele é para usar com os componentes que precisam de um rigidbody para funcionar, como os joints.
