### ISSUE TITLE
PrototypeScene V2 error  EventSystem

### ISSUE THREAD

**Issue by StefanWerW** [MuvucaGames/MuvucaGame01#72]
Acho que pelo fato da mudanças recentes no InputManager, alguns comandos padrões como **Submit** **Cancel**, e outros não existem mais, e por isso estão dando erro. Acho que uma correção é recolocar eles, mais não sei como eram, ou substituir os comandos no EventSystem de todos os prefabs que estão nos _prefabs->menu_

**Comment by rafaeljpc** [comment]
ok vou analisar e corrigir
